sentences:
  replicas: 1
  image:
    repository: releasepraqma/sentence
    tag: latest
  service:
    # type: ClusterIP
    type: NodePort
    nodePort: 31234
    port: 9090
    name: sentence
  resources:
    requests:
      cpu: 0.25
    limits:
      cpu: 0.25
